### ISSUE TITLE
Java-faili käivitamine (kompileerimine, käivitamine)

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#10]

**Comment by agoluberg** [comment]
https://github.com/tutjava/materjalid/blob/master/JavaFileRun.rst

**Comment by agoluberg** [comment]
Üks näide võiks olla käsureal ka selle kohta, kui projektis kasutatakse pakke. Siis ei ole tihti nii arusaadav, kuidas (millises kaustas) kompileerida. Käivitamisel tuleb samuti kasutada juba package1.package2.Main

**Comment by DenissPota** [comment]
Veel lahedam oleks panna lisaks screenshotid, kus käsurida ning need samad sammud, et käivitada mingi koodijupp. Siis oleks väga lihtne aru saada, mis üldse toimub. Arvatavasti on selliseid screenshotte ka netil üleval.

**Comment by brittapung** [comment]
Lisasin näited pakkide kohta ja tegin command line'ist screenshotid.

**Comment by britamoorus** [comment]
Kas nende üksikute ridade screenshottide asemel poleks vb parem kirjutada lihtsalt `C:Users\User\TUTJava\src\>javac Add.java`
