### ISSUE TITLE
Javadoc

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#11]
Kust näeb javadoc'i? Mismoodi seda lugeda? IDE info võiks olla vastava IDE lehel.

**Comment by brittapung** [comment]
https://github.com/tutjava/materjalid/blob/master/Javadoc2.rst

**Comment by mhaalme** [comment]
Akki võiks olla mingi lühike õpetus, mis õpetab genereeritud javadoci lugema ka, nt et lehe alguses on kirjas väljade nimekiri, seejärel alles meetodite nimekiri ning allpool detailsem ülevaade. Ja siis mainida, et seal neid välju ja meetodeid pole välja toodud, mis ülemklassidelt või liidestelt päritakse.

Ma pole kindel, kas see on täpselt selle teema juures aktuaalne. Kuna java dokumentatsioon on ka üks suur javadoc, siis oleks mõistlik selgitada, millist infot ta sisadab. Mulle vähemalt oli alguses jube segane, kui polnud varem kokku puutunud.
