### ISSUE TITLE
Pakid, teegid

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#13]
Lühike kirjeldus, mis on pakk/teek.

**Comment by KertOjasaar** [comment]
https://github.com/tutjava/materjalid/blob/master/Package.rst

**Comment by agoluberg** [comment]
Siin võiks tuua täpsema näite, et mida tähendab "klass kuulub kuhugi paketti". Võiks konkreetselt failistruktuuri näite tuua. Päris paljudel algajatel tekitab see suurt segadust.

**Comment by KertOjasaar** [comment]
Lisasin pildi.
