### ISSUE TITLE
Muutuja

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#14]

**Comment by KertOjasaar** [comment]
https://github.com/tutjava/materjalid/blob/master/Muutuja.rst

**Comment by agoluberg** [comment]
Siin võiks natuke seletada, mis asi see muutuja üldse on. Siis võiks lisada, et Javas on muutujal alati ka andmetüüp. Võiks mainida erienvat tüüpi muutujaid, nagu näiteks siin:https://docs.oracle.com/javase/tutorial/java/nutsandbolts/variables.html
Samamoodi võiks kirjutada natuke ka nimetamisest.
Lisaks võiks väga lühidalt kirjutada primitiivse andmetüübi muutujast vs objekti muutujast. Mõlemad sisuliselt hoiavad väärtust. Üks muutuja väärtust, teine viidet mällu. Võid panna viite siia (selline üle keskmise populaarne küsimus/vastus): http://stackoverflow.com/questions/40480/is-java-pass-by-reference-or-pass-by-value

**Comment by KertOjasaar** [comment]
Kasutasin veidi teistsugust linki, aga lisasin veidi kirjeldust.
