### ISSUE TITLE
Primitiivne andmetüüp

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#15]

**Comment by britamoorus** [comment]
[materjalid/PrimitiveDataTypes.rst](https://github.com/tutjava/materjalid/new/master)

**Comment by agoluberg** [comment]
Pane siia koodinäide ka, kuidas igat tüüpi muutujat teha. Vägapõhjalikult pole vaja. Hiljem lisame lingi numbriliste tüüpide juurde (seal on väga hästi juba oluline info välja toodud). Aga mingi kiire info võiks siin ka olla.

**Comment by britamoorus** [comment]
Tegin mõned näited juurde, ei hakanud väga põhjalikumalt tegema kuna põhjalikum selgitus on numbriliste tüüpide juures.
