### ISSUE TITLE
Tõeväärtus-andmetüübid

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#17]

**Comment by britamoorus** [comment]
[materjalid/BooleanDataType.rst](https://github.com/tutjava/materjalid/blob/master/BooleanDataType.rst)

**Comment by agoluberg** [comment]
Siia võiks välja tuua tõeväärtuste tabeli põhioperatsioonidega. Näiteks nagu see: http://3.bp.blogspot.com/-mnDeONCDxuo/Th63hE_gYsI/AAAAAAAAAEc/nk7-dEtDO-o/s1600/and+or+not+truth+table.gif
Seda pilti panna ei tohi. Variant on teha tabelina või ise pildina.
Näiteid võiks olla selle kohta ka, kus väärtustamine on natuke keerukam kui lihtsalt a = true. Pigem mingi a = x > 10 || y < 10;
Näite puhul muidugi võiks mingi sisukama muutuja nime ka mõelda :) Aga siis peab näide ka vastav olema. A la boolean isWetAndCold = temperature > 0 && temperature < 10;
Natuke jääb segaseks ka see "meetodid" osa. Peaksid eelnevalt mainima, mis see Boolean on. Väga pikalt ehk ei pea siin seletama. Tekitame selle jaoks täitsa eraldi lehe, kus räägime primitiivsetest andmetüüpidest ja nende wrapperitest.
Lisaks võiks siin näide olla ka sellest, if/while/for jne konstruktsioonid kasutavad boolean väärtust, et otsustada, kas käivitada mingit koodiosa. Ja seal kasutatav kontroll võib olla kas lihtne boolean muutuja väärtuse kontroll või mingi keerukam avaldis (aga selle tulemus peab ikka olema kas true või false).
Mulle on tundunud, et tudengitele on natuke see boolean'i osa segaseks jäänud. Üldiselt näidete põhjal saadakse aru lihtsast olukorrast: if (a > 10). Aga kui läheb keerukmakas, siis tekivad probleemid. Ja võib-olla tasub mainida ka, et sellist asja pole vaja kirjutada: if (b == true). Kui b on boolean, piisab if (b) jne.

**Comment by britamoorus** [comment]
Tegin juurde põhioperatsioonide peatüki, lisasin ühe keerukama väärtustamise näite. Tegin stiili kohta peatüki ja näidistabeli. Tegin tingimuslausete peatüki ka juurde.
Keegi võiks selle meetodite osa veel ehk üle vaadata. Lisasin sinna lühikese seletuse wrapperi kohta koos mingi näitega.

**Comment by agoluberg** [comment]
Võib-olla neid Boolean meetodeid polegi vaja välja tuua. Ma ei tea kedagi, kes neid kasutaks (kõik asjad saab loogikaavaldiste ja primitiividega tehtud). Samas, las nad olla. Muus osas tundub korras. Aitäh!
