### ISSUE TITLE
Tsüklid

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#19]

**Comment by britamoorus** [comment]
[materjalid/Loop.rst](https://github.com/tutjava/materjalid/blob/master/Loop.rst)

**Comment by agoluberg** [comment]
Siia võiks proovida ühe näite ka forEach'iga teha. Näiteks siit mõni lihtsam: https://www.mkyong.com/java8/java-8-foreach-examples/

**Comment by britamoorus** [comment]
Lisasin juurde kolm forEachi näidet listi, kujutise ja voo kohta.
