### ISSUE TITLE
Materjalide publitseerimine

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#2]
Tuleb välja mõelda, millist algformaati kasutada.

Siin on mõned lingid, mida võiks kaaluda:
http://ericholscher.com/blog/2016/mar/15/dont-use-markdown-for-technical-docs/
http://www.programmableweb.com/news/why-you-should-use-markdown-your-api-documentation/2015/02/19
http://dont-be-afraid-to-commit.readthedocs.io/en/latest/documentation.html
https://github.com/github/markup#markups

Võttes kõike arvesse, tundub reStructuredText kõige mõistlikum.

Tuleks leida vahend, millega saab lehed HTML-iks konvertida. Asjad, mida kontrollida/proovida:
 - kuidas lingid töötavad ühelt lehelt teisele
 - kuidas pildid teksti sees töötavad
 - missugune loodud html välja näeb (kas on vaja natuke css-i lisada)

**Comment by KertOjasaar** [comment]
Kui algformaadiks kasutada reStruc´turedText'i, siis seda saab konvertida HTML'i kasutades Docutilsi. Seal olemas rst2HTML.py ja muud sellised.

**Comment by Paksmagu** [comment]
ma midagi kiiresti vaatasin selle MD kohta, et sellele on ka olemas mingi md2HTML, kuid jh, rst tundub olema ovarall parem, tundub et on kergem kirjutada, samas ei ole täpsemalt vaadanud kuidas see HTML versioon välja tuleb kui convertida.
