### ISSUE TITLE
Meetod (funktsioon)

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#20]
Siin veel OOP-ist otseselt ei räägi. Pigem kirjeldada meetodit kui funktsiooni

**Comment by KertOjasaar** [comment]
https://github.com/tutjava/materjalid/blob/master/Method.rst

**Comment by agoluberg** [comment]
Siia võiks mingeid konkreetseid näited ka panna. 2-3 tükki, kus on erinevad tagastustüübid, parameetrid jms.

**Comment by KertOjasaar** [comment]
Lisasin erinevaid koodinäiteid.
