### ISSUE TITLE
Meetod ilma tagastustüübita (void)

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#21]

**Comment by KertOjasaar** [comment]
https://github.com/tutjava/materjalid/blob/master/VoidMethod.rst

**Comment by DenissPota** [comment]
Kert, ma pigem tooks ühe näite ka mitte-oopist, muidu need .this ja objekti loomised ei ole vist head niimodi kohe alguses võtta. Selles mõttes, nagu ma saan aru, void method, on üpris alguse osa, aga OOP on küll semestri keskpaik.

**Comment by DenissPota** [comment]
public class ExampleVoid {

   public static void main(String[] args) {
      methodStudentGrade(83);
   }

   public static void methodStudentGrade(double points) {
      if (points >= 91) {
         System.out.println("Grade is 5");
      }else if (points >= 81) {
         System.out.println("Grade is 4");
      }else {
System.out.println("Grade is 3 or lower");      }
   }
}
