### ISSUE TITLE
Meetodi tagastusväärtus

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#22]

**Comment by KertOjasaar** [comment]
https://github.com/tutjava/materjalid/blob/master/MethodReturnValue.rst

**Comment by mhaalme** [comment]
Mulle tundub imelik, et on kirjas Integer ja siis all on näites int. Tudengid küll alguses ei tea, et tagastusväärtus võib Integer objekt ka olla, aga hiljem võib see segadust tekitada.

**Comment by britamoorus** [comment]
Nõustun Mariliisiga, et võiks olla ehk lühike selgitus, et suure algustähega on objektid ja väikese algustähega on andmetüübid. Näited võiksid siis olla ikka väikeste algustähtedega

**Comment by KertOjasaar** [comment]
Muutsin selle ära.

**Comment by mhaalme** [comment]
Muutsin Listi arrayks kuna list ja massiiv on samuti erinevad asjad. Esimesel vaatamisel ei pannud tähele, aga nüüd hakkas silma.

**Comment by agoluberg** [comment]
Siia võiks sissejuhatusse paar rida kirjutada, mis see "tagastus" üldse on. Ehk siis kasutatakse "return" võtmesõna. Võiks mainida ka juhtu, kui tagasustüüp on "void" ja et ka siis võib "return" kasutada. "return" ise lõpetab funktsiooni täitmise ära.
