### ISSUE TITLE
Meetodi argumendid

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#23]

**Comment by KertOjasaar** [comment]
https://github.com/tutjava/materjalid/blob/master/MethodArguments.rst

**Comment by agoluberg** [comment]
Siin võiks lisaks olla näide ka selle kohta, kuidas välja kutsuda meetodit argumentidega.

**Comment by agoluberg** [comment]
Lisa meetodi väljakutse koodinäitesse järgmised olukorrad:

- argumendina antakse kaasa mingi avaldis (mitte lihtsalt 4, vaid näiteks 3 * 3 - 5 vms)
- argumendina antakse kaasa muutuja. aga võiks olla nii, et annad kaasa muutuja, mille nimi oleks sama mis meetodi parameeter. selliseid näiteid võiks olla kaks tükki. üks immutable andmetüübiga (näiteks String või int) ja teine näiteks mingi List. meetodi sees võiks vastavat parameetrit muuta. ja siis pärast meetodi väljakutset prindiks etteantud argumendi välja (et näidata, et ühel puhul muutub ja teisel mitte)

Praegu need koodinäited on kuidagi eraldiseisvad ja tudeng ei oska neid käima panna. addTwoNumbers on üldse mitte-static. main meetodis seda niisama ei saa käima panna. Pigem tee näited, kus on terve klass, seal sees meetod ja main-meetodis kasutamise näide. Ehk siis et tudeng saab kopeerida ja katsetada. Kommentaar pane ka inglisekeelseks (errori kohta).

**Comment by KertOjasaar** [comment]
Lisasin mõned asjad, aga ei saanud täpselt aru, mida mõtlesid teises punktis. 
Kas mõtled midagi sellist:
`private int myMethod(int myMethod) {`

**Comment by agoluberg** [comment]
Pigem nii et meetod on a la int getvalue(int box) {box++;}... ja kutsud välja:
Int box = 3;
Mingiklass.getvalue(box);
Print box

**Comment by agoluberg** [comment]
Moblaga ei saanud hästi kirjutada. Proovin natuke paremini nüüd.

Tahaks näidata seda, et kui meetodisse antakse kaasa mingi "muutuja", siis tegelikult antakse väärtus. Et kui sul on näiteks main'is muutuja "a" ja annad selle meetodisse, mis teeb a++, siis main-meetodis jääb a väärtuseks ikka algne väärtus. Meetodi väljakutsumise hetkel algväärtustatakse parameetrina märgitud nimi (näiteks a) ära kaasa antud väärtusega. See pole kuidagi seotud main-meetodis oleva muutujaga. Seda võiks näidata väljaprintidega (mainis enne meetodi väljaktuset, meetodi sees ja mainis peale meetodi väljakutset).

Teine näide võiks olla näiteks Listiga. Kui meetodis lisatakse mingi väärtus (meetod võibki olla addElementToList(List<Integer> list, int element). Ja nüüd kui main meetodis pärast meetodi väljakutset listi vaadata, siis seal on element juures. Selle näite puhul antakse ka tegelikult väärtus kaasa (mitte objekt). Väärtus (viide) objektile. Kuigi kui öeldakse, et antakse kaasa objekt, siis see otseselt vale pole.

**Comment by KertOjasaar** [comment]
Lisasin selle.

**Comment by agoluberg** [comment]
Veel selline mõte siin, et peaks äkki selle koodi jagama meetodite kaupa väiksemateks ja eesti keeles seletama natuke lahti, mis toimub. Terviklik koodinäide võib ka alla jääda.
