### ISSUE TITLE
Meetodi ülelaadimine

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#24]

**Comment by mhaalme** [comment]
https://github.com/tutjava/materjalid/blob/master/MethodOverload.rst

**Comment by agoluberg** [comment]
Siia võiks teha mingi alapeatüki, kus on paar näidet õigetest/valedest olukordadest. Näiteks nagu siin lehel http://beginnersbook.com/2013/05/method-overloading/ (scrolli allapoole kus on peatükk "Lets see few Valid/invalid cases ..."). Ma arvan, et seal need 5 näidet vist katavadki kõik erinevad olukorrad ära. Võib-olla sul tuleb endal mingi hea mõte veel.
Ja lisaks võiks äkki viidata jälle "Joshua Bloch's Effective Java" Item 41: Use overloading judiciously. Sealsed näited on päris keerulised. Aga üldine mõte on see, et ülelaadimisega ei tasuks liiale minna.
Kui pakub huvi, võid ise siit vaadata: https://github.com/HackathonHackers/programming-ebooks/tree/master/Java . Seal on viide olemas Effective Java pdf-versioonile. Aga tekstis seda pdf-i viidata ei tohi.

**Comment by mhaalme** [comment]
Lisasin näited ja viite. Polnud kindel, kas niimoodi lühidalt viitamisest piisab või peaks natuke rääkima ka,  millest seal juttu on.

**Comment by agoluberg** [comment]
Sedasi on hea. Aitäh!
