### ISSUE TITLE
Koodi moduleerimine

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#25]
Miks ja kuidas on mõistlik koodi struktureerida.

**Comment by mhaalme** [comment]
https://github.com/tutjava/materjalid/blob/master/CodeModularity.rst

Kas peaks mingeid näiteid tooma? Mul ei teki ühtegi ideed hea lühikese näite jaoks hetkel.

**Comment by britamoorus** [comment]
Äkki tasuks veel juurde kirjutada koodi taaskasutusest, et koodi moduleerides ja väksemateks juppideks jagades on võimalik koodi taaskasutada?

**Comment by mhaalme** [comment]
Lisasin vastava punkti.
