### ISSUE TITLE
Sõne

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#26]

**Comment by britamoorus** [comment]
[materjalid/String.rst](https://github.com/tutjava/materjalid/blob/master/String.rst)

**Comment by agoluberg** [comment]
Siin võiks rääkida, et String on immutable. Näiteks siin on hea näide: http://stackoverflow.com/questions/1552301/immutability-of-strings-in-java
ehk siis kui isegi paned viitama s2 = s1, siis ühte muutes teine ei muutu. Sest tegelikult "ühte muutes" mitte ei muudeta esimest, vaid tehakse uus objekt.

**Comment by britamoorus** [comment]
Lisasin näite ja lühikese selgituse _immutable_ kohta.

**Comment by agoluberg** [comment]
> "Sellisel juhul pole sõnel väärtust määratud. Vaikeväärtus on null."

Tegelikult String x; on initsialiseerimata muutuja. Kui seda teha lokaalselt (meetodi sees), siis sama muutuja kasutamisel enne sellele väärtuse määramist annab kompilaator vea. Pigem võib-olla näidata kohe algväärtusega sõne loomist (String x = "kõik jutud").

replace() juures võiks lisada, et tagastab **uue** sõne. Samamoodi tegelikult järgmiste kirjeldustega ka. Võiks rõhutada, et tagastatakse uus sõne (mõni muidu arvab, et muudetakse olemasolevat).

Sõne muutmise juures:

> Esimene objekt jääb sealjuures alles ega muutu

Võib-olla seda ei tasuks mainida. Üldiselt on nii, et kui objektile enam viidet pole, siis see kustutatakse mälust (aga seda ei pruugita teha kohe peale viida kadumist). Lisaks on sõnede puhul mingid erandid (_string pool_ jne). Seega võimalik, et see esimene sõne jääb mällu alles, aga seda garanteerida ei saa.

Muus osas on väga hea :)

**Comment by britamoorus** [comment]
Viisin muudatused sisse :)

**Comment by agoluberg** [comment]
Väga hea, aitäh!
