### ISSUE TITLE
Kogumid: järjend (List)

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#28]

**Comment by agoluberg** [comment]
https://github.com/tutjava/materjalid/blob/master/List.rst

**Comment by agoluberg** [comment]
Võiks mainida veel selliseid teemasid nagu: listi läbikäimine erineval moel, elemendi otsimine listist, lihtne sortimine (Collections.sort näitekst) ja list -> array. Näiteks sellelt lingilt võib saada näiteid: http://www.codejava.net/java-core/collections/java-list-collection-tutorial-and-examples
Ja võiks mainida, et lisaks ArrayList'ile on ka näiteks LinkedList, millel on kõik samad meetodid. Vahe on selles, et mingid operatsioonid on kiiremad/aeglasemad võrreldes ArrayListiga. Sealsamas lingil kohe alguses on paar lauset selle kohta. Tundub mõistlik see umbes kirja panna. Paljud ei saa aru ega mõtle selle peale (vähemalt esialgu mitte), osad aga saavad ja tasub kohe ära mainida.

**Comment by ojametsgh** [comment]
Lisasin erineveid viise kuidas listist läbi loopida, ja Sorti. Kirjutasin midagi ka selle LinkedListi kohta....
