### ISSUE TITLE
Kogumid: kujutis (Map)

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#30]

**Comment by ojametsgh** [comment]
https://github.com/tutjava/materjalid/blob/master/Map.rst

**Comment by agoluberg** [comment]
Pane koodis kommentaarid inglisekeelseks. Ning lisa lambda-näide ka: http://stackoverflow.com/a/19491759/122128

**Comment by ojametsgh** [comment]
Muutsin kommentaarid inglisekeelseks ning lisasin ka lambda näite

**Comment by brittapung** [comment]
Osad näite kommentaarid tunduvad segased/mitte päris õiged.

**Comment by ojametsgh** [comment]
Muutsin natukene kommentaare arusaadavamaks

**Comment by agoluberg** [comment]
Vaata mõned asjad üle. Näiteks teksti sees on HashMap deklareerimisel sulud () puudu. Sealsamas võiks pigem öelda, et K ja V on andmetüübid, mitte viited objektidele.

Olulisemate meetodite juures <code> on segane. Vaatasin, et see oli jäänud wikist vigane stiili tääg. Võta see <code> osa üldse ära.

Kuigi minu näide oli Integer, Integer seoste kohta, võiks teha mingi String, Integer näiteks. Seda praegust näidet saaks vajadusel ka array-ga teha (osad elemendid jäävad tühjaks).

Pane alla ka viide HashMap javadocile: https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html

**Comment by ojametsgh** [comment]
Muutsin koodi näite ära, kuid põhi idee jätsin samaks. Tegin veel teised väikesed parandused
