### ISSUE TITLE
Kogumid: kahemõõtmelised kogumid

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#31]

**Comment by brittapung** [comment]
https://github.com/tutjava/materjalid/blob/master/ListList.rst

**Comment by mhaalme** [comment]
Tegin nii, et konsooli väljatrüki näited oleks ühtlaselt musta värvi. Maatriksi näites võiks olla lõpus selline osa ka, kus mingil kindlal kohal asuva elemendi väärtus ära muudetakse. Muidu äkki mõeldakse, et peab uue massiivi looma või kuidagi selle massiivi muutuja kaudu tegema seda, kui tegelikult saab otse matrix[0][3] = 6 kirjutada.

**Comment by brittapung** [comment]
Hea mõte, kirjutasin juurde.

**Comment by britamoorus** [comment]
Võiks juurde olla kirjutatud mitmemõõtmelise massiivi pikkuse leidmise kohta. Muutsin kommentaarid inglise keelseks
