### ISSUE TITLE
Sisendi lugemine failist

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#33]

**Comment by ojametsgh** [comment]
https://github.com/tutjava/materjalid/blob/master/SisendiLugemineFileist.rst

**Comment by agoluberg** [comment]
Siin võiks natuke rääkida ka erindist ja faili sulgemisest. Erindid üldiselt on eraldi teemana olema (hiljem saab lingi lisada). Aga võiks välja tuua, millised põhilised erindid võivad tekkida (mis olukorras mis erind). Samuti siis sellest, et miks ja kuidas peaks faile sulgema.
Mõistlik oleks tuua selline näide ka: https://dzone.com/articles/java-7-new-feature-%E2%80%93 või http://docs.oracle.com/javase/7/docs/technotes/guides/language/try-with-resources.html
Pythonis osad tudengid ongi vaid sellisel kujul faile avanud.

**Comment by ojametsgh** [comment]
Lisasin ka Try-with-resources meetodi kõige esimeseks

**Comment by agoluberg** [comment]
Need näited, kus on eraldi close() meetodi väljakutse, pole väga head/korrektsed. Nimelt, kui enne sulgemist tekib viga, siis sulgemist ei toimugi. Tegelikult peaks ressursi sulgemine toimuma finally plokis. try-with-resource variandi puhul tehakse sulgemine automaatselt.

Üks "tavaline" näide Reader'iga peaks jääma, aga siis korrektselt, et on try-catch-finally ümber.

Ma pakun, et järgmised variandid peaks jääma:

- kõige klassikalisem buffered readeriga (nt. http://stackoverflow.com/a/4716623/122128 - kohe esimene koodinäide)
- Files.newBufferedReader variant (umbes nagu sul, aga korrektse finally osaga, kus tehakse close)
- Files.readAllLines (umbes nagu sul)
- Scanneriga (umbes nagu sul)
- lambda variant ka: https://www.mkyong.com/java8/java-8-stream-read-a-file-line-by-line/

Kõik näited võiksid olla näiteks main-meetodi sees, aga selgelt eraldatud. Kui neid jagada meetoditesse, läheb hea näite tegemine juba keerulisemaks (peaks meetodi sees tegelema veahaldusega, samuti meetodi väljakutsel; ning kuidas veahaldust teha, sõltub konkreetsest ülesandest).

**Comment by brittapung** [comment]
Minu arust võiksid kõik näited olla näiteks eraldi alapealkirjade all. Sellist pikka koodinäidet on tüütu lugeda, peab näpuga järge ajama.

**Comment by ojametsgh** [comment]
Muutsin koodi näidet ümber ja lisasin ka eraldi koodi näite kuidas manuaalselt kinni panna

**Comment by agoluberg** [comment]
Britta kommentaar on õige. Need koodinäited võiks eraldi teemade all olla. Iga näite kohta võiks paar rida teksti ka olla (mida Buffer teeb, mida Scanner jne).
