### ISSUE TITLE
OOP: objekti loomine

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#37]

**Comment by DenissPota** [comment]
https://github.com/tutjava/materjalid/blob/master/oopCreatingObject.rst

**Comment by britamoorus** [comment]
Parandasin veidi sõnastust

**Comment by agoluberg** [comment]
Vt näiteks sellist lehte: http://math.hws.edu/javanotes/c5/s1.html
seal on vahva joonis (kolmas joonis muutujate std, std1, std2, std3 kohta), kuidas Student mälus on. Võib-olla selline näide annaks mõnele edasi info, et näiteks kaks muutujat viitavad samale objektile jne. Selle raamatu pilti võib põhimõtteliselt viidata ka. Ehk siis võib päris sama näite panna. Või siis võid proovida ise mingi näite/pildi vms teha.

**Comment by DenissPota** [comment]
Lisasin sama näite

**Comment by agoluberg** [comment]
Tegin Student näite terviklikuks (koos klassiga) ja viitasin ka visualizerile.
