### ISSUE TITLE
OOP: konstruktor

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#38]

**Comment by DenissPota** [comment]
https://github.com/tutjava/materjalid/blob/master/oopConstructor.rst

**Comment by mhaalme** [comment]
1.  Kuna argumendita konstruktor ei ole default konstruktor, siis ajab segadusse, et seal prinditakse välja "This is a default constructor". Ja all ExampleTwo's samamoodi - ütlesid et default on ainult see, mida välja ei kirjutata, aga näites nimetad praegu argumentidega konstruktorit default konstruktoriks.
2. Actor klassi näites võiks olla vähemalt korra näidatud tervet Actor klassi koos tema väljade deklaratsiooniga. Pythonis sai nii teha, et konstruktoris deklareerid kõik muutujad esimest korda, aga Javas selline kood käima ei lähe ja tudeng ei pruugi aru saada, mis tal puudu on.

Parandasin mõned kirja-ja stiilivead ka ära.

**Comment by DenissPota** [comment]
Head märkused. Vahetasin "default" asja "parametrized" vastu ning tegin valmis actor klassi ja väljad. Igahates, parandasin :)

**Comment by agoluberg** [comment]
Tegin mõne koodi vormistuse korda. Muidu korras, tänud!
