### ISSUE TITLE
OOP: staatiline muutuja, meetod, konstant

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#39]

**Comment by DenissPota** [comment]
https://github.com/tutjava/materjalid/blob/master/oopStatic.rst

**Comment by agoluberg** [comment]
Lisaks süntaksi näitele "<class-name>.<method.name>" võiks olla ka konkreetne lihtne koodinäide. Samuti välja kohta.
Ja siin kohe on küsimus visibility kohta. Kas välja tuua ka see aspekt või mitte. Kui ühes näites on määramata ja teises on private, võib tekitada küsimusi.
Üks variant on esialgu näited teha public'uga.
Samuti võiks olla konstant (final). Et neid märksõnu ikka maksimaalselt saaks kasutada :)

**Comment by DenissPota** [comment]
Muutsin

**Comment by agoluberg** [comment]
See Stuff ja count on hea näide, aga võiks koodis välja tuua ka selle osa, kuidas see töötab. Ehk siis main meetod, kus reaalselt tehakse paar objekti ja pärast prinditakse välja, mis count on. Siis saab tudeng koodi käima panna ja katsetada. Muidu jääb natuke liiga abstraktseks.
Teine asi, konstandi alla võiks paari sõnaga mainida _magic number_ probleemi (nt et koodis 42 ei ole mõistlik ega arusaadav, aga MEANING_OF_LIFE on palju selgem - aga võid natuke sisukama näite tuua :) ). See küsimus neil tekib kindlasti, siis saab mugavalt viidata sellel osale.

**Comment by DenissPota** [comment]
Hea mõte. Lisasin mõlemad soovitused.
