### ISSUE TITLE
OOP: objekt muutujas, argumendina kaasa andmine

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#41]

**Comment by mhaalme** [comment]
https://github.com/tutjava/materjalid/blob/master/oopObjectAsVariable.rst

**Comment by agoluberg** [comment]
Koodinäites tahad vist muuta p1 koordinaate, aga kogemata muudad p2 y-koordinaadi ka ära.

Palun pane sellise koodinäite peale ka väljund. Mõni ei hakka käima panema, aga väljundi järgi saab paremini aru, mis toimub.

Ja võib-olla võiks see teine näide ollagi selline, mis muudab peale printimist x-koordinaadi 0-ks. Või ajaks see pigem asjad segaseks?

**Comment by mhaalme** [comment]
Parandasin koodinäite ära ja lisasin väljundi, mille tegin samuti veidi loetavamaks.

Teise näite puhul ei tahaks print-funktsiooni sisse koordinaadi muutmist panna, kuna see oleks sisult ebaloogiline. Selline näide oleks iseenesest vajalik küll, kus argumendina saadud objektis midagi muudetakse. Printimise näide polegi nii oluline. Ma mõtlen homme veel natuke selle peale, kuidagi võiks ümber teha.

**Comment by mhaalme** [comment]
Tegin näited uuesti korda. Ma jätsin printimise näite alles ja tegin eraldi muutmise näite ning paigutasin nad eraldi alajaotustesse. Proovisin kõik näited läbi ka ja nüüd peaks korras olema.

**Comment by agoluberg** [comment]
Nii on väga hea, aitäh!
