### ISSUE TITLE
OOP: this

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#43]

**Comment by ojametsgh** [comment]
https://github.com/tutjava/materjalid/blob/master/oopThis.rst

**Comment by agoluberg** [comment]
Tee koodinäites ka üks selline muutuja, mida kohalik muutuja ära ei peida. Võiks tuua välja, et sellisel juhul this'i ei pea kasutama, aga võib.

**Comment by agoluberg** [comment]
ja siis võiks näide olla ka meetodi kohta. Samamoodi, et kutsutakse välja this ja ilma this'ita.

**Comment by ojametsgh** [comment]
Lisasin kohaliku muutuja mida ei peideta.

**Comment by agoluberg** [comment]
Võid teha näiteks Student'ile meetodi initializeGrades(), mille sisu ei peagi otseselt tegema. Pane lihtsalt mingi kommentaar a la "here we initialize student's grades". Lisaks võiks mingi teine meetod olla, näiteks enroll() (samamoodi sisu pole oluline). Konstruktoris võiks siis ühe meetodi kustuda this'iga, teise ilma.

**Comment by agoluberg** [comment]
Tegelt tuleks lisada ka konstruktori väljakutse näide, a la https://docs.oracle.com/javase/tutorial/java/javaOO/thiskey.html
Ehk siis teed mingi teise konstruktori ja kutsud this'iga välja.

**Comment by ojametsgh** [comment]
Tegin meetodi kohta ja lisasin ka veel konstruktori näite

**Comment by agoluberg** [comment]
Sa nüüd muutsid natuke Student konstruktorit. Vaata eelnev tekst ka üle.

Koodinäites ei tohiks kommentaarid nii pikaks minna (mingi reapikkuse piirang on). Pigem pane kommentaar eelnevatele ridadele. Vajadusel pane kommentaar kahele reale (kui läheb liiga pikaks).

Vaata üle, et sa teeksid vahet klassi ja objekti muutujal/meetodis. Paaris kohas kommentaaris jäi silma, et sa räägid klassi meetodist (staatiline meetod). Tegelikult võiks kirjutada objekti või instantsi meetod.

**Comment by ojametsgh** [comment]
Muutsin commentid lühemks ja lisasin teksti natukene juurde.

**Comment by mhaalme** [comment]
Parandasin paar kirjaviga ja tegin mõne koha paremini arusaadavaks.
