### ISSUE TITLE
OOP: encapsulation

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#45]
lühidalt kirjeldada OOP printsiipi.

**Comment by heleriinots** [comment]
https://github.com/tutjava/materjalid/blob/master/oopEncapsulation.rst

**Comment by agoluberg** [comment]
Palun tee koodinäide selliseks, et seda saab käima panna. Selleks kas kirjeldad Dishwasher'i ka ära või kasutad mingit olemasolevat Java objekti. Samuti võiksid koodinäites printida väärtused välja (ja kaasa panna ka väljundi). Hetkel sa kutsud getter-meetodid välja, aga kuidagi ei saa kontrollida, mis seal sees on.

Muus osas on korras.

**Comment by heleriinots** [comment]
Lisasin vajaliku
