### ISSUE TITLE
OOP: polymorphism

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#47]
lühidalt kirjeldada OOP printsiipi.

**Comment by ojametsgh** [comment]
https://github.com/tutjava/materjalid/blob/master/oopPolymorphism.rst

**Comment by agoluberg** [comment]
Vaata tekst üle. Väga palju on kirjavigu.

Näide võiks olla kas javafx Color'iga (praegu on java.awt) või siis üldse mingi abstraktsem (teed enda Color'i või kasutad mingit String'i näiteks).

**Comment by britamoorus** [comment]
Ma kirjutaks juurde, milliseid polümorfismi liike on olemas ja tooks nende kohta eraldi näited. Praegune näide on võib-olla veidi segane
