### ISSUE TITLE
OOP: alamklassid

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#48]

**Comment by DenissPota** [comment]
https://github.com/tutjava/materjalid/blob/master/oopSubclass.rst

**Comment by mhaalme** [comment]
Getterite ja setterite kohta võiks mingi näide olla, kui neid juba mainitakse. Sul vist kuskil failis oli see olemas; ehk tasuks sellele viidata, kuna muidu ei oska kuskilt otsida.

Tekstis on öeldud "kirjutatakse meetod üle @Override", mis viitab justkui @Override annotatsiooni kasutamisele, aga samas allpool näites on näha, et seda pole vaja lisada. Kas siis on vaja või ei ole? Seda võiks seletada.

**Comment by DenissPota** [comment]
Lisasin getterite, setterite näited, lisasin @Override anotatsiooni, kuna seda on väga mõistlik kasutada.

**Comment by agoluberg** [comment]
Võiks mainida seda, et kui pöördutakse mingi meetodi poole (someObject.someMethod()), siis otsitakse seda kõigepealt someObject instantsist. Kui seal pole, siis selle ülemklassis jne. Kuni object klassini välja. 

Lisaks see see Animal ja Cat näide on static meetoditega. Sa vist mõtlesid ikka mitte-staatilisi meetodeid?

**Comment by DenissPota** [comment]
Lisasisn someObject.someMethod() asja, ning võtsin static maha, see oli typo vist.
