### ISSUE TITLE
OOP: super

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#49]

**Comment by DenissPota** [comment]
https://github.com/tutjava/materjalid/blob/master/oopSuper.rst

**Comment by mhaalme** [comment]
Muutsin viimase lõigu sõnastust, et oleks arusaadavam. Leidsin üles lõigu, mida ilmselt tõlkida proovisid ja tegin selle põhjal. Võib-olla peaks seda ka mainima, et kui ühtegi konstruktorit pole defineeritud, siis päritakse see Object klassilt ja seetõttu ei teki kompilatsiooniviga vms

**Comment by DenissPota** [comment]
Parandasin!

**Comment by agoluberg** [comment]
Ferrari kiiruse näites võiks mainida, mis üldse juhtub, kui mõlemas klassis on "speet" muutuja. Ehk siis et üks peidab teise ära. Koodinäites võiks printida ka "this.speed" või "speed" lihtsalt välja. Et siis on näha, et need on erinevad. A la "Usual vehicle speed is: " + speed.

MountainBike'i näite kohta pane ka Bicycle koodinäide (kus on vastavad konstrukturid). Samamoodi siis MountainBike klass ise, kus on ka see seatHeight.

**Comment by agoluberg** [comment]
Vaata eelmist kommentaari.

**Comment by DenissPota** [comment]
Ups. Unustasin selle asja parandamise täitsa ära. Täiendasin seda ferrari näidet ja lisasin Bicycle ja Mountainbike täielikud näited.
