### ISSUE TITLE
git kasutamine

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#5]

**Comment by britamoorus** [comment]
[materjalid/Git.rst](https://github.com/tutjava/materjalid/blob/master/Git.rst)

**Comment by agoluberg** [comment]
Palun pane juurde ka peatükk giti kasutamisest TTÜ-s. Näiteks umbes nii: https://courses.cs.ttu.ee/pages/ITI0011:git#git.27i_kasutamine_aines või nii: https://courses.cs.ttu.ee/w/images/d/da/ITI0011-2016_Git.pdf
Esialgu on tudengil mugav, kui ta konkreetse näite, kuidas koodi giti panna. Küll hiljem nad kasutamise käigus hakkavad vaikselt aru saama, mis toimub.

**Comment by britamoorus** [comment]
Lisasin peatüki Git'i kasutamisest TTÜ-s

**Comment by britamoorus** [comment]
Kas mul oleks mõtet kirjutada ka git log võimalusest?

**Comment by agoluberg** [comment]
git log'ist pole vaja kirjutada. Las Kert vaatab ka veel üle.

**Comment by agoluberg** [comment]
Väga hea, tänud!
