### ISSUE TITLE
OOP: override, overload

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#50]

**Comment by DenissPota** [comment]
https://github.com/tutjava/materjalid/blob/master/oopOverrideVsOverload.rst

**Comment by britamoorus** [comment]
Parandasin sõnastust ja mõned kirjavead. Muutsin veel tekstis override ülekirjutamiseks ja overload'i ülelaadimiseks.

**Comment by agoluberg** [comment]
Tee ülekirjutamise kohta näide, kus ühel juhul annab meetod tulemuseks 3 ja teisel 4.

**Comment by DenissPota** [comment]
Lisasin käivituse.
