### ISSUE TITLE
OOP: erilised meetodid toString, equals jne

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#51]

**Comment by mhaalme** [comment]
https://github.com/tutjava/materjalid/blob/master/oopSpecialMethods.rst

Oleks hea, kui keegi targem inimene vaataks mõttega üle equals ja hashcode osa. Ma pole 100% kindel, et olen kõigest õigesti aru saanud.

**Comment by agoluberg** [comment]
Kõik on õige ja väga hea. Võib-olla võiks tuua näite, kuidas ainult equals implementeerides HashMap annab vale tulemuse. A la teed HashMap<Point, Integer>. Paned new Point(0, 0)-le mingi väärtuse. Ja pärast küsid get(new Point(0, 0)). Kui hashCode pole õigesti implementeeritud, peaksid tulemuseks saama null (mitte oodatud Integer'i).
Ja võib veel panna viite sellisesse kohta nagu "Joshua Bloch's Effective Java Item 7, Item 8 (chapter 3)". Otsest viidet sinna vist ei anna panna. Kuigi see on kättesaadav näiteks siit: https://courses.cs.washington.edu/courses/cse373/12sp/homework/6/ch3_effectivejava-excerpt.pdf
Aga autoriõigus arvatavasti ei luba selliselt viidata. Seega võiks olla lihtsalt tekstina. Võid veel mõne viite panna, kui leiad. Samast peatükist saab Item 9-t viidata toString osas.

**Comment by agoluberg** [comment]
Saad palun teha selle näite, kus equals ja hashcode pole mõlemad implementeeritud. Saaksin selle issue kinni panna.

**Comment by mhaalme** [comment]
Teen hiljemalt täna öösel ära, hetkel olen eemal kahjuks.

**Comment by mhaalme** [comment]
Lisasin näite, pidin oma hashCode'i ka natuke muutma ja lisasin selgituse, miks see vajalik on. Taaskord loodan, et sain ikka õigesti aru.

Viited lisasin ka, aga panin peatükkide numbrid 2nd editioni põhjal. Need on ühe võrra nihkes võrreldes esimesega ja 2nd editioni pdf on kergesti leitav, kui otsingusse panna.

**Comment by agoluberg** [comment]
Aitäh!
