### ISSUE TITLE
Erind

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#53]

**Comment by brittapung** [comment]
https://github.com/tutjava/materjalid/blob/master/Exceptions.rst

**Comment by agoluberg** [comment]
Siia võiks tegelikult lisada sellise näite, kus on vähemalt kaks catch plokki. Tudeng võiks aru saada, et täpsema erindi peab eespool püüdma (muidu rakendub üldisem). Samuti võiks finally plokist rääkida.
