### ISSUE TITLE
JavaFX: üldine

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#55]

**Comment by heleriinots** [comment]
https://github.com/tutjava/materjalid/blob/master/JavaFXGeneral.rst

**Comment by mhaalme** [comment]
Parandasin paar kirjaviga ja komaviga, asendasin mõne termini eestikeelse vastega ja panin paar semikoolonit ka, et pikad laused oleks arusaadavamad.

**Comment by agoluberg** [comment]
Korras, tänud!
