### ISSUE TITLE
JavaFX: baasstruktuur/hello world

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#56]

**Comment by heleriinots** [comment]
https://github.com/tutjava/materjalid/blob/master/JavaFXBasicStructure.rst

**Comment by agoluberg** [comment]
Võiksid siia lisada pildi http://docs.oracle.com/javase/8/javafx/get-started-tutorial/hello_world.htm lehelt (kus on stage, scene jne). Sellesama pildi kohal on struktuuri kirjeldus. Võiksid sealt ka mõned mõtted kirja panna. Tudeng võiks saada lisaks koodile ka natuke aru, kuidas asjad toimivad.

**Comment by heleriinots** [comment]
Lisasin vajaliku info juurde.

**Comment by agoluberg** [comment]
Väga hea, aitäh!
