### ISSUE TITLE
IntelliJ kasutamine

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#6]

**Comment by KertOjasaar** [comment]
https://github.com/tutjava/materjalid/blob/master/IntellijTut.rst

**Comment by britamoorus** [comment]
Ma paneks võib-olla kolmanda punkti juurde OS X puhul JDK kausta asukoha ka (tavaliselt /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home). Mõni võibki seda muidu otsima jääda.

**Comment by KertOjasaar** [comment]
Lisasin selle.

**Comment by agoluberg** [comment]
Siia võiks panna mõned viited. Näiteks alustuseks see, et kust intelliJ saab alla laadida. Võiks panna ka eraldi viite, et kuidas tudengina saab ultimate litsentsi (https://www.jetbrains.com/student/).
Siis võiks viidata näiteks projekti käivitamise osa: https://www.jetbrains.com/help/idea/2016.3/running-applications.html . Neil on tegelikult väga mõistlik help olemas - ei olegi vaja seda ringi teha. Aga kindlasti võiks all olla viited. Võib-olla nii, et on viide kogu dokumentatsioonile: https://www.jetbrains.com/help/idea/2016.3
Aga lisaks võiks välja tuua mingid konkreetsemad teemad:
https://www.jetbrains.com/help/idea/2016.3/keyboard-shortcuts-you-cannot-miss.html
https://www.jetbrains.com/help/idea/2016.3/guided-tour-around-the-user-interface.html
Täitsa eraldi teema on veel projekti/moodulite seadistamine. Neil on variant teha iga ülesande jaoks eraldi projekt. Aga siis peab uue akna avama. Mõnele võib-olla see sobib. Teine variant on teha projekti alla moodulid. Siis näiliselt saab kõiki projekte ühes aknas käivitada ja vaadata. Sa võiks proovida selle kohta mõne lause kirjutada. Võib-olla saad ka help'ist midagi vastavat viidata.

**Comment by KertOjasaar** [comment]
Lisasin.
