### ISSUE TITLE
JavaFX: animation

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#60]

**Comment by heleriinots** [comment]
https://github.com/tutjava/materjalid/blob/master/JavaFXAnimation.rst

**Comment by mhaalme** [comment]
Mul miskipärast ei õnnestu viimast näidet tööle saada. Kas seal peaks midagi teistmoodi tegema kui teiste näidete puhul?

**Comment by agoluberg** [comment]
Heleriin, saad palun vaadata, mis selle viimase näitega on? Saaks selle asja kinni panna :)
