### ISSUE TITLE
JavaFX: events (key, mouse, etc)

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#61]

**Comment by ojametsgh** [comment]
https://github.com/tutjava/materjalid/blob/master/JavaFXEventHandler.rst

**Comment by agoluberg** [comment]
Siin võiksid panna Event alamklasside pildinäite siit: http://docs.oracle.com/javafx/2/events/processing.htm

Vaata üle, sa oled kirjutanud, et Event tüüpe on kolm. Pigem saaks öelda, et KeyEvent tüüpe on kolm. 

Ilma lambdata handleri kohta võiks mainida ka, et tegemist on anonüümse klassiga.

Event kohta ütle pigem sündmus, kui sa ei viita just konkreetselt klassi/tüübi nimele

**Comment by KertOjasaar** [comment]
Parandasin mõned kirjavead.

**Comment by ojametsgh** [comment]
Parandasin ja lisasin pildi

**Comment by agoluberg** [comment]
Koodinäites võiks ikka import laused ka olla - et saab kopi-paste käima panna.

**Comment by ojametsgh** [comment]
Panin import laused juurde
