### ISSUE TITLE
Ühiktestimine

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#62]

**Comment by ojametsgh** [comment]
https://github.com/tutjava/materjalid/blob/master/%C3%9Chiktestimine.rst

**Comment by heleriinots** [comment]
Ma parandasin kirjavigu ning kirjutasin teksti paaris kohas natuke ringi, et jutt oleks (loodetavasti) pisut arusaadavam. Lisaks sellele oleks vahava, kui sa lisaksid veel mõned illustreerivad koodinäited.

**Comment by agoluberg** [comment]
Siin peaks TestNG-st mingi näite tooma. Minu video on juniti kohta. Kindlasti tuleb kunagi video TestNG kohta ka. Aga igal juhul võiks mingi lihtsam koodinäide olla. Põhimõtteliselt sa võid proovida näiteks sedasama date validatorit testida TestNG-ga.
Kui vaja, võin saata sulle need kaks faili (DateValidator ja DateValidatorTest). Test peaks siis TestNG raamistikku kasutama.

**Comment by ojametsgh** [comment]
Muutsin koodi näite ümber TestNG peale ning tegin selle DateValidatori järgi. Muutsin ka eelnevalt natukene kuidas lisada dependancit.

**Comment by agoluberg** [comment]
Lisa alla viide testng enda veebilehele ka.

Lisaks võiksid tekstis proovida eestikeelseid sõnu kasutada. Näiteks jäävad silma sellised asjad
- "setup'ib" => näiteks "seadistab"
- "test class" => "testiklass"
- "displaytakse" => "kuvatakse" või "näidatakse välja"

Neid on arvatavasti veel. Proovi kõik sellised ära asendada eestikeelsete sõnadega. Kui kuskil on viide meetodile, siis see võib loomulikult jääda inglisekeelseks.

Lisa siis juba üks pilt ka: http://blog.caplin.com/wp-content/uploads/068_-_Unit-testing1.png

**Comment by agoluberg** [comment]
ja pane selline viide ka lõppu: http://stackoverflow.com/questions/67299/is-unit-testing-worth-the-effort
Seal on päris hästi seletatud, miks ühiktestimine üldse vajalik on.

**Comment by agoluberg** [comment]
Saad palun viimati mainitud asjad lisada/parandada?

**Comment by ojametsgh** [comment]
Lisasin uued asjad ja parandasin natukene eesti keelseks

**Comment by agoluberg** [comment]
vist sai valmis :)
