### ISSUE TITLE
Koodistiil

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#7]

**Comment by britamoorus** [comment]
[materjalid/CodeStyle.rst](https://github.com/tutjava/materjalid/blob/master/CodeStyle.rst)

**Comment by KertOjasaar** [comment]
Kas ma näen ise valesti või ongi _Vormistus_ blokis esimene koodinäide vigane?
Parandasin ühe tabulatsiooni hooletusvea ära real 122.

**Comment by britamoorus** [comment]
See koodinäide on selline üldine lihtsalt, et näidata kuidas need loogelised sulud paiknema peaksid.

**Comment by agoluberg** [comment]
Selles Vormistuse näites on lõpus üleliigune semikoolon.

Siin võiks viite panna ka checkstyle viite. Ning paari lausega kirjeldada, kuidas IntelliJ-s saab selle peale panna.

Muidu on väga hea ülevaatlik. Kõiki erinevaid probleeme ei saagi välja tuua. Ja kui avastame tudengitel mingid tüüpvead, eks siis täiendame vastavalt.

**Comment by britamoorus** [comment]
Lisasin teksti checkstyle kohta.
