### ISSUE TITLE
Java-faili ülesehitus

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#8]

**Comment by KertOjasaar** [comment]
https://github.com/tutjava/materjalid/blob/master/JavaFileStructure.rst

**Comment by britamoorus** [comment]
Tuleks ehk juurde kirjutada, et faili struktuur koosneb paketi deklaratsioonsist (valikuline), import lausest (valikuline) ja klassi definitsioonist. 
http://etutorials.org/shared/images/tutorials/tutorial_161/02fig02.gif

Lisaks oleks vb koodinäide lihtsamini loetavam ilma docstringita?

**Comment by DenissPota** [comment]
Nõustun Britaga, et Javadoc on sobilik juhul, kui on kirjeldatud ära, mis asi see javadoc on. Kasvõi ühe lausega. Muidu võib seda lugeda, kui koodirida, mis ei ole tõsi.

Samuti veel see statement võib-olla annaks ka midagi: If the name of the class defined in the file is A then the file must be named A.java.

**Comment by KertOjasaar** [comment]
Lisasin need.

**Comment by agoluberg** [comment]
See Brita viidatud pilt on tegelikult väga hea. Võiksid lisaks tekstile ka proovida sarnase asja siia panna. Võid ka vabalt teha koodinäite, kus kommentaaridega oled eraldanud erinevad osad.

**Comment by KertOjasaar** [comment]
Algselt jäi Brita viidatud pilt kahe silma vahele. 
Lisasin pildi ning panin paar selgitavat kommentaari. Mõtlesin mingi reaalse impordi ka teha näiteks _Random_ näol, kuid see võib algajates segadusi tekitada, et mis asi see selline on ja miks nii kasutatakse. Seega jätsin impordi välja, kuid panin kommentaari, kus need olema peaks.
