### ISSUE TITLE
Java projekti ülesehitus

### ISSUE THREAD

**Issue by agoluberg** [tutjava/materjalid#9]

**Comment by KertOjasaar** [comment]
https://github.com/tutjava/materjalid/blob/master/JavaProjectStructure.rst

**Comment by agoluberg** [comment]
Sul näites on tegelikult 4 klassi. Võiks vastavalt teksti muuta. Ja natuke võiks rääkida, miks Main on otse src kaustas (õigemini, mida see tähendab ehk n-ö unnamed package või ka default package). Siin võiks ära ka mainida selle, et üldiselt on normaalne, kui seda nimeta pakki ei kasutata. Aga väikeste projektide puhul on see mõistlik.
Võid vaadata järgmisi linke: http://stackoverflow.com/questions/7849421/is-the-use-of-javas-default-package-a-bad-practice ja http://stackoverflow.com/questions/2193226/how-to-import-a-class-from-default-package
Ehk siis miks default package pole nii mõistlik. Aga kui on vaid mõned klassid, siis võiks ok olla (nagu üldiselt meie java ülesanded)

**Comment by KertOjasaar** [comment]
Parandasin ja lisasin.
